/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.gob.senescyt.snna;

/**
 *
 * @author jchalan
 */
public class EncuestaContexto extends javax.swing.JFrame {

    /**
     * Creates new form Encuesta
     */
    public EncuestaContexto() {
        initComponents();
        
        buttonGroup_1.add(resp_100);
        buttonGroup_1.add(resp_101);
        buttonGroup_1.add(resp_102);
        
        buttonGroup_2.add(resp_103);
        buttonGroup_2.add(resp_104);
        buttonGroup_2.add(resp_105);
        
        jLayeredPane_2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_1 = new javax.swing.ButtonGroup();
        buttonGroup_2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane_1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        resp_100 = new javax.swing.JRadioButton();
        resp_101 = new javax.swing.JRadioButton();
        resp_102 = new javax.swing.JRadioButton();
        jLayeredPane_2 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        resp_103 = new javax.swing.JRadioButton();
        resp_104 = new javax.swing.JRadioButton();
        resp_105 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane_1.setBackground(new java.awt.Color(0, 204, 255));
        jLayeredPane_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayeredPane_1MouseClicked(evt);
            }
        });
        jLayeredPane_1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLayeredPane_1MouseMoved(evt);
            }
        });

        jLabel1.setText("1.- ¿ Pregunta Uno ?");

        resp_100.setText("Respuesta Uno");
        resp_100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resp_100MouseClicked(evt);
            }
        });
        resp_100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resp_100ActionPerformed(evt);
            }
        });

        resp_101.setText("Respuesta Dos");

        resp_102.setText("Respuesta Tres");

        jLayeredPane_1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_1.setLayer(resp_100, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_1.setLayer(resp_101, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_1.setLayer(resp_102, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane_1Layout = new javax.swing.GroupLayout(jLayeredPane_1);
        jLayeredPane_1.setLayout(jLayeredPane_1Layout);
        jLayeredPane_1Layout.setHorizontalGroup(
            jLayeredPane_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane_1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resp_100)
                    .addGroup(jLayeredPane_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(resp_102)
                        .addComponent(jLabel1)
                        .addComponent(resp_101, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jLayeredPane_1Layout.setVerticalGroup(
            jLayeredPane_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane_1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resp_100)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resp_101)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resp_102)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane_2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel2.setText("2.- ¿ Pregunta Dos ?");

        resp_103.setText("Respuesta Cuatro");

        resp_104.setText("Respuesta Cinco");
        resp_104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resp_104ActionPerformed(evt);
            }
        });

        resp_105.setText("Respuesta Seis");
        resp_105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resp_105ActionPerformed(evt);
            }
        });

        jLayeredPane_2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_2.setLayer(resp_103, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_2.setLayer(resp_104, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_2.setLayer(resp_105, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane_2Layout = new javax.swing.GroupLayout(jLayeredPane_2);
        jLayeredPane_2.setLayout(jLayeredPane_2Layout);
        jLayeredPane_2Layout.setHorizontalGroup(
            jLayeredPane_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane_2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(resp_104)
                    .addComponent(resp_103)
                    .addComponent(resp_105))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane_2Layout.setVerticalGroup(
            jLayeredPane_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane_2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resp_103)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resp_104)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resp_105)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(956, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jTabbedPane1.addTab("Sección Uno", jScrollPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sección Dos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resp_104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resp_104ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resp_104ActionPerformed

    private void resp_100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resp_100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resp_100ActionPerformed

    private void resp_100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resp_100MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_resp_100MouseClicked

    private void jLayeredPane_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane_1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLayeredPane_1MouseClicked

    private void jLayeredPane_1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayeredPane_1MouseMoved
        // TODO add your handling code here:
        if(resp_100.isSelected()){
            jLayeredPane_2.setVisible(true);
        }else{
            jLayeredPane_2.setVisible(false);
        }
    }//GEN-LAST:event_jLayeredPane_1MouseMoved

    private void resp_105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resp_105ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resp_105ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncuestaContexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncuestaContexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncuestaContexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncuestaContexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncuestaContexto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_1;
    private javax.swing.ButtonGroup buttonGroup_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane_1;
    private javax.swing.JLayeredPane jLayeredPane_2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton resp_100;
    private javax.swing.JRadioButton resp_101;
    private javax.swing.JRadioButton resp_102;
    private javax.swing.JRadioButton resp_103;
    private javax.swing.JRadioButton resp_104;
    private javax.swing.JRadioButton resp_105;
    // End of variables declaration//GEN-END:variables
}
